export const FETCH_WORKING_HOURS_REQUEST = 'FETCH_WORKING_HOURS_REQUEST'
export const FETCH_WORKING_HOURS_SUCCESS = 'FETCH_WORKING_HOURS_SUCCESS'
export const FETCH_WORKING_HOURS_FAILURE = 'FETCH_WORKING_HOURS_FAILURE'

export const STORE_WORKING_HOUR_REQUEST = 'STORE_WORKING_HOUR_REQUEST'
export const STORE_WORKING_HOUR_SUCCESS = 'STORE_WORKING_HOUR_SUCCESS'
export const STORE_WORKING_HOUR_FAILURE = 'STORE_WORKING_HOUR_FAILURE'

export const UPDATE_WORKING_HOUR_REQUEST = 'UPDATE_WORKING_HOUR_REQUEST'
export const UPDATE_WORKING_HOUR_SUCCESS = 'UPDATE_WORKING_HOUR_SUCCESS'
export const UPDATE_WORKING_HOUR_FAILURE = 'UPDATE_WORKING_HOUR_FAILURE'

export const DESTROY_WORKING_HOUR_REQUEST = 'DESTROY_WORKING_HOUR_REQUEST'
export const DESTROY_WORKING_HOUR_SUCCESS = 'DESTROY_WORKING_HOUR_SUCCESS'
export const DESTROY_WORKING_HOUR_FAILURE = 'DESTROY_WORKING_HOUR_FAILURE'